# Generated by Django 3.2.2 on 2021-05-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('courses', models.ManyToManyField(null=True, to='courses.Course')),
            ],
        ),
    ]
